import xss from 'xss';

const myxss = new xss.FilterXSS({
	whiteList: {
		a: ['href', 'title', 'target'],
		u: [],
		br: [],
		b: [],
		i: [],
		ol: ['style'],
		ul: ['style'],
		li: [],
		p: ['style'],
		sub: [],
		sup: [],
		div: ['style'],
		em: [],
		strong: [],
		span: ['style'],
		ins: [],
	},
});

export const myContentXSS = new xss.FilterXSS({
	whiteList: {
		a: ['href', 'title', 'target', 'style', 'class'],
		abbr: ["title"],
		address: [],
		area: ["shape", "coords", "href", "alt"],
		article: [],
		aside: [],
		b: [],
		big: [],
		blockquote: ["cite"],
		br: [],
		caption: [],
		center: [],
		cite: [],
		code: [],
		col: ["align", "valign", "span", "width"],
		colgroup: ["align", "valign", "span", "width"],
		dd: [],
		del: ["datetime"],
		details: ["open"],
		div: ['style', 'class'],
		dl: ['style', 'class'],
		dt: ['style', 'class'],
		em: [],
		figcaption: [],
		figure: [],
		font: ["color", "size", "face"],
		footer: [],
		h1: ['style', 'class'],
		h2: ['style', 'class'],
		h3: ['style', 'class'],
		h4: ['style', 'class'],
		h5: ['style', 'class'],
		h6: ['style', 'class'],
		header: [],
		hr: [],
		i: [],
		img: ["src", "alt", "title", "width", "height", "loading"],
		ins: ["datetime"],
		li: ['style', 'class'],
		mark: [],
		nav: [],
		ol: ['style', 'class'],
		p: ['style', 'class'],
		pre: [],
		s: [],
		section: [],
		small: [],
		span: ['style', 'class'],
		strike: [],
		strong: [],
		sub: [],
		summary: [],
		sup: [],
		table: ["width", "border", "align", "valign"],
		tbody: ["align", "valign"],
		td: ["width", "rowspan", "colspan", "align", "valign"],
		tfoot: ["align", "valign"],
		th: ["width", "rowspan", "colspan", "align", "valign"],
		thead: ["align", "valign"],
		tr: ["rowspan", "align", "valign"],
		tt: [],
		u: [],
		ul: ['style', 'class'],
	},
});

export default myxss;
